In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
df=pd.read_json("https://raw.githubusercontent.com/onaio/ona-tech/master/data/water_points.json")
df

,water_pay,respondent,research_asst_name,water_used_season,_bamboo_dataset_id,_deleted_at,water_point_condition,_xform_id_string,other_point_1km,_attachments,...,animal_point,water_mechanism_plate,water_lift_mechanism_type,road_type,water_mechanism_plate_units,water_mechanism_plate_no,water_not_functioning,water_source_type_other,simserial,subscriberid
0,no,community,Haruna Mohammed,year_round,,NaT,functioning,_08_Water_points_CV,no,[north_ghana/attachments/1351696546452.jpg],...,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,no,community,Haruna Mohmmed,year_round,,NaT,functioning,_08_Water_points_CV,yes,[north_ghana/attachments/1351701849971.jpg],...,yes,no,manual_power,gravel,NaN,NaN,NaN,NaN,NaN,NaN
2,no,community,Haruna Mohammed,year_round,,NaT,functioning,_08_Water_points_CV,yes,[north_ghana/attachments/1351702462336.jpg],...,yes,no,manual_power,paved,NaN,NaN,NaN,NaN,NaN,NaN
3,no,community,Haruna Mohammed,year_round,,NaT,functioning,_08_Water_points_CV,yes,[north_ghana/attachments/1351702971561.jpg],...,yes,no,manual_power,paved,NaN,NaN,NaN,NaN,NaN,NaN
4,no,community,Haruna Mohammed,year_round,,NaT,functioning,_08_Water_points_CV,yes,[north_ghana/attachments/1351703622326.jpg],...,yes,no,manual_power,paved,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,no,community,Emmanuel y,year_round,,NaT,functioning,_08_Water_points_CV,no,[north_ghana/attachments/1358151218133.jpg],...,yes,no,hand_pump,NaN,NaN,NaN,NaN,NaN,NaN,NaN
708,no,local_authority community,Emmanuel y,year_round,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1358081512606.jpg],...,yes,no,hand_pump,NaN,NaN,NaN,NaN,NaN,NaN,NaN
709,no,local_authority community,Emmanuel y,year_round,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1358081512606.jpg],...,yes,no,hand_pump,NaN,NaN,NaN,NaN,NaN,NaN,NaN
710,no,community,abu seidu,year_round,,NaT,functioning,_08_Water_points_CV,no,[north_ghana/attachments/1358175596571.jpg],...,yes,no,hand_pump,NaN,NaN,NaN,NaN,NaN,8.923301e+18,6.200101e+14
711,no,community,Sa,year_round,,NaT,functioning,_08_Water_points_CV,yes,[north_ghana/attachments/1355488003808.jpg],...,yes,no,manual_power,gravel dirt,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
from collections import Counter

In [4]:
#counting the number of water points that are functional
functional= df.water_point_condition.value_counts()['functioning']
print("THE NUMBER OF WATER POINTS THAT ARE FUNCTIONING", functional)

#the new added points
new_points= df.water_point_condition.value_counts()['newly_constructed']
print("THE NUMBER OF NEW WATER POINTS  ",new_points )

#ASSUMING THE NEW POINTS ARE FUNCTIONING
functioning_points=functional+new_points
print("THE NUMBER OF WATER POINTS THAT ARE FUNCTIONING + NEW POINTS",functioning_points )

THE NUMBER OF WATER POINTS THAT ARE FUNCTIONING 590
THE NUMBER OF NEW WATER POINTS   28
THE NUMBER OF WATER POINTS THAT ARE FUNCTIONING + NEW POINTS 618

In [5]:
#the number of water points per community
community= df.respondent.value_counts()['community']
print("THE NUMBER OF WATER POINTS IN community",community)

local_authority_community= df.respondent.value_counts()['local_authority community']
print("THE NUMBER OF WATER POINTS IN local_authority_community",local_authority_community)

THE NUMBER OF WATER POINTS IN community 640
THE NUMBER OF WATER POINTS IN local_authority_community 55

In [9]:
filter_criteria =(df['respondent'] == 'community' )& (df['water_point_condition'] == 'broken')
df1m = df[filter_criteria]

print(df1m.shape)
#counting the community water point is broken
community= df1m.water_point_condition.value_counts()['broken']

print('total number of broken points in %:', community/100)


df1m.head(10)

(34, 48)
total number of broken points in %: 0.34

,water_pay,respondent,research_asst_name,water_used_season,_bamboo_dataset_id,_deleted_at,water_point_condition,_xform_id_string,other_point_1km,_attachments,...,animal_point,water_mechanism_plate,water_lift_mechanism_type,road_type,water_mechanism_plate_units,water_mechanism_plate_no,water_not_functioning,water_source_type_other,simserial,subscriberid
64,no,community,HM,cannot_determine,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1351776609118.jpg],...,no,no,manual_power,NaN,NaN,NaN,kiosk_broken,NaN,NaN,NaN
65,no,community,HM,cannot_determine,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1351777083828.jpg],...,no,no,manual_power,NaN,NaN,NaN,kiosk_broken,NaN,NaN,NaN
66,no,community,HM,cannot_determine,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1351777431416.jpg],...,no,no,manual_power,NaN,NaN,NaN,kiosk_broken,NaN,NaN,NaN
79,na_dn,community,HM,cannot_determine,,NaT,broken,_08_Water_points_CV,no,[north_ghana/attachments/1351783689341.jpg],...,no,no,pump_mini_grid,gravel,NaN,NaN,kiosk_broken,NaN,NaN,NaN
87,no,community,HM,cannot_determine,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1351858359523.jpg],...,no,yes,hand_pump,NaN,horsepoower,6445.0,kiosk_broken,NaN,NaN,NaN
97,no,community,HM,cannot_determine,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1351861396658.jpg],...,no,no,hand_pump,NaN,NaN,NaN,kiosk_broken,NaN,NaN,NaN
100,no,community,HM,cannot_determine,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1351869869630.jpg],...,no,NaN,NaN,NaN,NaN,NaN,kiosk_broken,NaN,NaN,NaN
102,no,community,HM,cannot_determine,,NaT,broken,_08_Water_points_CV,no,[north_ghana/attachments/1351870696537.jpg],...,no,no,manual_power,NaN,NaN,NaN,kiosk_broken,NaN,NaN,NaN
114,no,community,HM,cannot_determine,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1351935992321.jpg],...,yes,yes,hand_pump,gravel,horsepoower,19983.0,kiosk_broken,NaN,NaN,NaN
120,no,community,HM,cannot_determine,,NaT,broken,_08_Water_points_CV,no,[north_ghana/attachments/1351938018751.jpg],...,no,yes,hand_pump,NaN,horsepoower,19983.0,kiosk_broken,NaN,NaN,NaN

In [10]:
filter_criteria =(df['respondent'] == 'local_authority community' )& (df['water_point_condition'] == 'broken')
df3m = df[filter_criteria]

print(df3m.shape)
#counting the community water point is broken
local_authority_community = df3m.water_point_condition.value_counts()['broken']

print('total number of broken points in %:',local_authority_community /100)


df3m.head(10)

(5, 48)
total number of broken points in %: 0.05

,water_pay,respondent,research_asst_name,water_used_season,_bamboo_dataset_id,_deleted_at,water_point_condition,_xform_id_string,other_point_1km,_attachments,...,animal_point,water_mechanism_plate,water_lift_mechanism_type,road_type,water_mechanism_plate_units,water_mechanism_plate_no,water_not_functioning,water_source_type_other,simserial,subscriberid
61,no,local_authority community,HM,cannot_determine,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1351775583470.jpg],...,no,no,manual_power,NaN,NaN,NaN,kiosk_broken,NaN,NaN,NaN
261,no,local_authority community,HM,cannot_determine,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1352061371378.jpg],...,no,no,hand_pump,NaN,NaN,NaN,kiosk_broken,NaN,NaN,NaN
264,no,local_authority community,HM,year_round,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1352062516469.jpg],...,no,no,hand_pump,NaN,NaN,NaN,kiosk_broken,NaN,NaN,NaN
708,no,local_authority community,Emmanuel y,year_round,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1358081512606.jpg],...,yes,no,hand_pump,NaN,NaN,NaN,NaN,NaN,NaN,NaN
709,no,local_authority community,Emmanuel y,year_round,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1358081512606.jpg],...,yes,no,hand_pump,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
filter_criteria =(df['respondent'] == 'local_authority' )& (df['water_point_condition'] == 'broken')
df2m = df[filter_criteria]

print(df2m.shape)
#counting the community water point is broken
local_authority = df2m.water_point_condition.value_counts()['broken']

print('total number of broken points in %:', local_authority/100)


df2m.head(10)

(1, 48)
total number of broken points in %: 0.01

,water_pay,respondent,research_asst_name,water_used_season,_bamboo_dataset_id,_deleted_at,water_point_condition,_xform_id_string,other_point_1km,_attachments,...,animal_point,water_mechanism_plate,water_lift_mechanism_type,road_type,water_mechanism_plate_units,water_mechanism_plate_no,water_not_functioning,water_source_type_other,simserial,subscriberid
51,no,local_authority,Hm,cannot_determine,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1351771347164.jpg],...,no,no,hand_pump,NaN,NaN,NaN,lift_broken,NaN,NaN,NaN

In [14]:
#creating a new dataframe

data = {'Name':['community','local_authority','local_authority_community'], 'Percentage':[0.34, 0.01,0.05]}

df_rank = pd.DataFrame(data)
df_rank['default_rank'] = df_rank['Percentage'].rank()
#df_rank['max_rank']= df_rank['Percentage'],[rank(method='max')]

print(df_rank)

                        Name  Percentage  default_rank
0                  community        0.34           3.0
1            local_authority        0.01           1.0
2  local_authority_community        0.05           2.0